Re-generated baseline with newly detected issues
As detected by `vimeo/psalm:^5`, these errors
are caused by invalid parsing of author collections:

```
ERROR: InvalidArgument - src/Reader/Entry/Rss.php:140:17 - Argument 1 of Laminas\Feed\Reader\Collection\Author::__construct expects array<int, array{name: string, ...<array-key, mixed>}>|null|object, but list{array{email?: string, name?: mixed|string}, ...<int<0, max>, array{email?: string, name?: mixed|string}>} provided (see https://psalm.dev/004)
                Reader\Reader::arrayUnique($authors)

ERROR: InvalidArgument - src/Reader/Extension/Atom/Entry.php:75:17 - Argument 1 of Laminas\Feed\Reader\Collection\Author::__construct expects array<int, array{name: string, ...<array-key, mixed>}>|null|object, but list{array{email?: null|string, name?: null|string, uri?: null|string}, ...<int<0, max>, array{email?: null|string, name?: null|string, uri?: null|string}>} provided (see https://psalm.dev/004)
                Reader\Reader::arrayUnique($authors)

ERROR: InvalidArgument - src/Reader/Extension/Atom/Feed.php:66:17 - Argument 1 of Laminas\Feed\Reader\Collection\Author::__construct expects array<int, array{name: string, ...<array-key, mixed>}>|null|object, but list{array{email?: null|string, name?: null|string, uri?: null|string}, ...<int<0, max>, array{email?: null|string, name?: null|string, uri?: null|string}>} provided (see https://psalm.dev/004)
                Reader\Reader::arrayUnique($authors)

ERROR: InvalidArgument - src/Reader/Feed/Rss.php:125:17 - Argument 1 of Laminas\Feed\Reader\Collection\Author::__construct expects array<int, array{name: string, ...<array-key, mixed>}>|null|object, but list{array{email?: string, name?: mixed|string}, ...<int<0, max>, array{email?: string, name?: mixed|string}>} provided (see https://psalm.dev/004)
                Reader\Reader::arrayUnique($authors)

```

An "author" needs to have at least a name, but the parsing logic can generate
an `array{name?: string, email?: string}`, which is not pricise enough.

We will **NOT** touch this for now, and limit ourselves to acknowledging the
problem as part of baseline expansion.

This change also removes a structural test that is very much validated by static
analysis, nowadays.